from dotenv import load_dotenv
import os


load_dotenv()

class Config:
    HOST = os.getenv("HOST")
    PORT = os.getenv("PORT")

    API_URL = os.getenv("API_URL")

    ZODIACS = {
        "Aries": {
            "glyph": "♈",
            "symbol": "Ram",
            "degrees": "000°–030°",
            "dates": "March 21 - April 19",
            "dates_leap_year": "March 20 - April 18",
            "season": "Spring",
            "sign_type": "Fire",
            "modality": "Cardinal",
            "polarity": "Masculine",
            "natural_house": 1,
            "traditional_ruler": "Mars",
            "modern_ruler": None,
            "opposite_sign": "Libra",
            "tarot_card": "The Emperor",
            "body_part": "Head, brain, face",
            "custom_text": "Fire sign, ruled by Mars"
        },
        "Taurus": {
            "glyph": "♉",
            "symbol": "Bull",
            "degrees": "030°–060°",
            "dates": "April 20 - May 20",
            "dates_leap_year": "April 19 - May 19",
            "season": "Spring",
            "sign_type": "Earth",
            "modality": "Fixed",
            "polarity": "Feminine",
            "natural_house": 2,
            "traditional_ruler": "Venus",
            "modern_ruler": None,
            "opposite_sign": "Scorpio",
            "tarot_card": "The Hierophant",
            "body_part": "Neck, throat, vocal cords",
            "custom_text": "Earth sign, ruled by Venus"
        },
        "Gemini": {
            "glyph": "♊",
            "symbol": "Twins",
            "degrees": "060°–090°",
            "dates": "May 21 - June 20",
            "dates_leap_year": "May 20 - June 19",
            "season": "Spring",
            "sign_type": "Air",
            "modality": "Mutable",
            "polarity": "Masculine",
            "natural_house": 3,
            "traditional_ruler": "Mercury",
            "modern_ruler": None,
            "opposite_sign": "Sagittarius",
            "tarot_card": "The Lovers",
            "body_part": "Arms, hands, lungs, nervous system",
            "custom_text": "Air sign, ruled by Mercury"
        },
        "Cancer": {
            "glyph": "♋",
            "symbol": "Crab",
            "degrees": "090°–120°",
            "dates": "June 21 - July 22",
            "dates_leap_year": "June 20 - July 21",
            "season": "Summer",
            "sign_type": "Water",
            "modality": "Cardinal",
            "polarity": "Feminine",
            "natural_house": 4,
            "traditional_ruler": "Moon",
            "modern_ruler": None,
            "opposite_sign": "Capricorn",
            "tarot_card": "The Chariot",
            "body_part": "Chest, breasts, stomach, digestive system",
            "custom_text": "Water sign, ruled by the Moon"
        },
        "Leo": {
            "glyph": "♌",
            "symbol": "Lion",
            "degrees": "120°–150°",
            "dates": "July 23 - August 22",
            "dates_leap_year": "July 22 - August 21",
            "season": "Summer",
            "sign_type": "Fire",
            "modality": "Fixed",
            "polarity": "Masculine",
            "natural_house": 5,
            "traditional_ruler": "Sun",
            "modern_ruler": None,
            "opposite_sign": "Aquarius",
            "tarot_card": "Strength",
            "body_part": "Heart, spine, upper back",
            "custom_text": "Fire sign, ruled by the Sun"
        },
        "Virgo": {
            "glyph": "♍",
            "symbol": "Maiden",
            "degrees": "150°–180°",
            "dates": "August 23 - September 22",
            "dates_leap_year": "August 22 - September 21",
            "season": "Summer",
            "sign_type": "Earth",
            "modality": "Mutable",
            "polarity": "Feminine",
            "natural_house": 6,
            "traditional_ruler": "Mercury",
            "modern_ruler": None,
            "opposite_sign": "Pisces",
            "tarot_card": "The Hermit",
            "body_part": "Abdomen, intestines, spleen",
            "custom_text": "Earth sign, ruled by Mercury"
        },
        "Libra": {
            "glyph": "♎",
            "symbol": "Scales",
            "degrees": "180°–210°",
            "dates": "September 23 - October 22",
            "dates_leap_year": "September 22 - October 21",
            "season": "Autumn",
            "sign_type": "Air",
            "modality": "Cardinal",
            "polarity": "Masculine",
            "natural_house": 7,
            "traditional_ruler": "Venus",
            "modern_ruler": None,
            "opposite_sign": "Aries",
            "tarot_card": "Justice",
            "body_part": "Lower back, kidneys, skin",
            "custom_text": "Air sign, ruled by Venus"
        },
        "Scorpio": {
            "glyph": "♏",
            "symbol": "Scorpion",
            "degrees": "210°–240°",
            "dates": "October 23 - November 21",
            "dates_leap_year": "October 22 - November 20",
            "season": "Autumn",
            "sign_type": "Water",
            "modality": "Fixed",
            "polarity": "Feminine",
            "natural_house": 8,
            "traditional_ruler": "Mars",
            "modern_ruler": "Pluto",
            "opposite_sign": "Taurus",
            "tarot_card": "Death",
            "body_part": "Reproductive organs, genitals, excretory system",
            "custom_text": "Water sign, ruled by Mars and Pluto"
        },
        "Sagittarius": {
            "glyph": "♐",
            "symbol": "Archer",
            "degrees": "240°–270°",
            "dates": "November 22 - December 21",
            "dates_leap_year": "November 21 - December 20",
            "season": "Autumn",
            "sign_type": "Fire",
            "modality": "Mutable",
            "polarity": "Masculine",
            "natural_house": 9,
            "traditional_ruler": "Jupiter",
            "modern_ruler": None,
            "opposite_sign": "Gemini",
            "tarot_card": "Temperance",
            "body_part": "Hips, thighs, liver, sciatic nerve",
            "custom_text": "Fire sign, ruled by Jupiter"
        },
        "Capricorn": {
            "glyph": "♑",
            "symbol": "Sea-Goat",
            "degrees": "270°–300°",
            "dates": "December 22 - January 19",
            "dates_leap_year": "December 21 - January 18",
            "season": "Winter",
            "sign_type": "Earth",
            "modality": "Cardinal",
            "polarity": "Feminine",
            "natural_house": 10,
            "traditional_ruler": "Saturn",
            "modern_ruler": None,
            "opposite_sign": "Cancer",
            "tarot_card": "The Devil",
            "body_part": "Knees, joints, bones, skeletal system",
            "custom_text": "Earth sign, ruled by Saturn"
        },
        "Aquarius": {
            "glyph": "♒",
            "symbol": "Water Bearer",
            "degrees": "300°–330°",
            "dates": "January 20 - February 18",
            "dates_leap_year": "January 19 - February 17",
            "season": "Winter",
            "sign_type": "Air",
            "modality": "Fixed",
            "polarity": "Masculine",
            "natural_house": 11,
            "traditional_ruler": "Saturn",
            "modern_ruler": "Uranus",
            "opposite_sign": "Leo",
            "tarot_card": "The Star",
            "body_part": "Ankles, calves, circulatory system",
            "custom_text": "Air sign, ruled by Saturn and Uranus"
        },
        "Pisces": {
            "glyph": "♓",
            "symbol": "Fish",
            "degrees": "330°–360°",
            "dates": "February 19 - March 20",
            "dates_leap_year": "February 18 - March 19",
            "season": "Winter",
            "sign_type": "Water",
            "modality": "Mutable",
            "polarity": "Feminine",
            "natural_house": 12,
            "traditional_ruler": "Jupiter",
            "modern_ruler": "Neptune",
            "opposite_sign": "Virgo",
            "tarot_card": "The Moon",
            "body_part": "Feet, toes, lymphatic system",
            "custom_text": "Water sign, ruled by Jupiter and Neptune"
        }
    }


config = Config